### ISSUE TITLE
Proxy is not used

### ISSUE THREAD

**Issue by SimonIT** [elmoiv/azapi#11]
Your get method has a parameter for setting the proxy for the request:

https://github.com/elmoiv/azapi/blob/8f3d44b6a9e26f7c6b6473391e4f9b8bec43d3a3/azapi/requester.py#L48

But you don't pass the proxy defined in the `AZlyrics` class to the method:

https://github.com/elmoiv/azapi/blob/8f3d44b6a9e26f7c6b6473391e4f9b8bec43d3a3/azapi/azapi.py#L77

https://github.com/elmoiv/azapi/blob/8f3d44b6a9e26f7c6b6473391e4f9b8bec43d3a3/azapi/azapi.py#L148

https://github.com/elmoiv/azapi/blob/8f3d44b6a9e26f7c6b6473391e4f9b8bec43d3a3/azapi/tools.py#L51-L55

**Comment by elmoiv** [comment]
Thanks for pointing this bug out.
I will fix it ASAP.

**Comment by elmoiv** [comment]
Updated the missing code.
Try to `pip install azapi==3.0.6` and please confirm if your issue was solved.

**Comment by SimonIT** [comment]
I suppose it's fixed. I hadn't an issue with it but an user of spotifylyrics had it probably
