### ISSUE TITLE
Error 404 getting lyrics

### ISSUE THREAD

**Issue by jack-debug** [elmoiv/azapi#12]
I am using azapi on a Google Colabatory runtime and using the example given in the readme returns an Error 404. Am I doing something wrong? What could be causing this?
<img width="392" alt="Screen Shot 2021-02-24 at 1 49 43 pm" src="https://user-images.githubusercontent.com/55571956/108940343-4d188280-76a7-11eb-906b-efb5b0d85119.png">

**Comment by elmoiv** [comment]
I tried it right now and it seems to run ok.

The code responsible for this error:
```python
if page.status_code != 200:
    print('Error 404!')
    return 1
```

As you see, this only happens at your side and have nothing to do with `azapi`.

You may be trying to send many requests which made Google temporarily block your requests, Or you may have issues with connecting to Google.

Try to use Duckduckgo search instead:
```python
API = azapi.AZlyrics('duckduckgo', accuracy=0.5)
```

Feel free to re-open this issue if you need more info :)

**Comment by z404** [comment]
Hi, I still get this error. Switching to duckduckgo gave me a new error

```python
Error 404!
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fbda66f9a20>
transport: <_SelectorSocketTransport fd=19 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

```

Is there any way to fix this?
