### ISSUE TITLE
getSongs doesn't work with certain artists

### ISSUE THREAD

**Issue by jgc37** [elmoiv/azapi#2]
Don't know if this is an issue with azlyrics but when trying to get the songs from someone like Kanye it only works if you search "West".  The terms "Kanye West" or "Kanye" throw errors.

**Comment by elmoiv** [comment]
This is an issue with _Azlyrics_ website. They stored **_Kanye West_** as **_West_** in their database.
The format of the singer url is `https://www.azlyrics.com/{First letter}/{Name}.html`, so it will be: https://www.azlyrics.com/w/west.html

I am adding soon **the search feature** which may help in situations like yours.

Sorry for facing this issue.

**Comment by jgc37** [comment]
Ok sounds good.  Other than that the api works really well.

**Comment by elmoiv** [comment]
#### You can now do this:

```python
from azapi import AZlyrics

api = AZlyrics()

songs = api.getSongs('Kanye', True)

print(songs)
```

Cheers ✌😊

**Comment by elmoiv** [comment]
> Don't know if this is an issue with azlyrics but when trying to get the songs from someone like Kanye it only works if you search "West". The terms "Kanye West" or "Kanye" throw errors.

#### You can now do this:

```python
from azapi import AZlyrics

api = AZlyrics()

songs = api.getSongs('Kanye', True)

print(songs)
```

Cheers ✌😊
