### ISSUE TITLE
Google or Duckduckgo found nothing

### ISSUE THREAD

**Issue by abhijitmaji27** [elmoiv/azapi#23]
Failed to find lyrics. Trying to get link from Google
Google found nothing!

**Comment by vladfreeze** [comment]
Also doesn't work for me

**Comment by elmoiv** [comment]
I tested it with random artists and it is working fine for both DuckDuckGo and Google.

You can comment with a snippet of your code to help solve your issue.

**Comment by vladfreeze** [comment]
I tested with the python example from the documentation. With google it worked only once, duckduckgo works correctly.

![image](https://user-images.githubusercontent.com/58890859/211218728-2d1b6ef1-88c0-4926-8d0c-95681c4dd1eb.png)

**Comment by abhijitmaji27** [comment]
I did the same code but after few requests Google is blocking the requests
so can you please tell me how to bypass the block

**Comment by elmoiv** [comment]
That happened due too many requests in a small duration. Try to wait for like a minute between each call.

> *It is adviced not to send too many requests to avoid IP ban by search engines.

If you have the correct artist and song name you can use direct fetch instead.

P.S: Try to use multiple proxies

**Comment by abhijitmaji27** [comment]
Thank you for your response.
