### ISSUE TITLE
.getSongs() TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by deepbluesea** [elmoiv/azapi#3]
**Describe the bug**
```
----> 1 songs = api.getSongs()

1 frames
/usr/local/lib/python3.6/dist-packages/azapi/AZtools.py in filtr(inpt, isFile)
     14     if isFile:
     15         return ''.join(i for i in inpt if i not in r'<>:"/\|?*')
---> 16     return ''.join(i.lower() for i in inpt if i.lower() in letters)
     17 
     18 def ParseLyric(page):

TypeError: 'NoneType' object is not iterable
```
**To Reproduce**
`from azapi import AZlyrics

api = AZlyrics('Taylor Swift')

songs = api.getSongs()
`

**Expected behavior**
self explanatory

**Comment by deepbluesea** [comment]
fixed with
api = AZlyrics()
api.getSongs('Taylor Swift')

**Comment by elmoiv** [comment]
When initializing `AZlyrics` class, you must pass both `artist` and `title` args.
but for `getSongs()`, `artist` should be passed to this function if not given to the initializer.

**Comment by elmoiv** [comment]
I updated `azapi.py` to avoid passing a `NoneType` object.
If your problem is solved, kindly close this issue :)
