### ISSUE TITLE
[Solved] getSongs() returns relative path

### ISSUE THREAD

**Issue by SimonIT** [elmoiv/azapi#6]
**Describe the bug**
`getSongs()` returns relative paths to the individual songs

**To Reproduce**
```python
    api = azapi.AZlyrics('duckduckgo', accuracy=0.5)

    api.artist = "Oliver Heldens"
    api.title = "Lift Me Up"

    songs = api.getSongs()
```
**Expected behavior**
The url is _https://www.azlyrics.com/lyrics/oliverheldens/liftmeup.html_

**Screenshots**
![image](https://user-images.githubusercontent.com/11720038/86769396-65238f00-c04f-11ea-8c7a-94edcb13a9f6.png)

**Desktop (please complete the following information):**
 - Version 3.0.0

**Comment by elmoiv** [comment]
Thanks. I will work on a fix

**Comment by elmoiv** [comment]
@SimonIT 
I patched a workaround for this bug.
Check it out and if your problem is solved, kindly close this issue :)

**Comment by SimonIT** [comment]
Yes, it's fixed. Thank you

**Comment by SimonIT** [comment]
Hey @elmoiv,
the problem somehow returned. I'm using version 3.0.6
![image](https://user-images.githubusercontent.com/11720038/147853346-c615085f-37d1-4b16-91d6-94faccc68865.png)

**Comment by elmoiv** [comment]
Can you please send the code producing this bug?

**Comment by SimonIT** [comment]
You can use the code from the first comment or this:
https://github.com/SimonIT/spotifylyrics/blob/a7d8df22f6398e50d49ef2300714d409bbf42905/services.py#L319-L342

**Comment by elmoiv** [comment]
@SimonIT 
Bug Patched.
Now `pip install azapi==3.0.7` and check if it's resolved at your side.

**Comment by SimonIT** [comment]
It's working again, thanks!
I wouldn't mind if the url would start with 'https', but that's only a minor detail
