### ISSUE TITLE
Feature Request: specify directory when saving lyrics

### ISSUE THREAD

**Issue by AlVincentM** [elmoiv/azapi#7]
Allowing ```getLyrics()``` to receive the desired directory as a string parameter to save the downloaded lyrics would be nice

**Comment by elmoiv** [comment]
Thanks for your request. Will be added in the Next Update :)

**Comment by AlVincentM** [comment]
Thanks! I am having fun using your azapi. sing along for dayzzzzzz

**Comment by elmoiv** [comment]
Hey @AlVincentM ,

Added your desired feature in the new update [v3.0.2](https://github.com/elmoiv/azapi/releases/tag/3.0.2) with a bunch of tweaks.

Cheers :)
